#!/usr/bin/env bash
#All Steps Creating A HHTP Response Header

sudo apt-get update
sudo apt-get install -y nginx


echo "Holberton School" | sudo tee /var/www/html/index.html

string_for_replacemen="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/FoibeU permanent;"
sudo sed -i "s/server_name _;/$string_for_replacemen/" /etc/nginx/sites-enabled/default

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
new_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$new_string/" /etc/nginx/sites-enabled/default


sudo sed -i "/server_name _/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

# Testing configurations for syntax errors
sudo nginx -t

# Restart nginx after implementing changes
