#!/usr/bin/env bash
#Checker for commandline arguments

if [ $# -lt 4 ];
then
  echo "Usage: $1 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
       exit 1
fi

# Assigning variable to a parameter

Path_to_file=$1
IP=$2
username=$3
path_to_ssh_key=$4

# disabbling strict host key checking

scp -o "StrictHostKeyChecking no" -i "$path_to_ssh_key" "$username@$ip:~/"

#checking id the transfer was successful
if [$? -eq 0]
then
	echo "FILE WAS TRANSFERED SUCCESSFULLY"
else
	echo "FILE TRANSFER FAILED"
fi
