#!/usr/bin/env bash
# commands to  install  Nginx on web server.

sudo apt-get  update
sudo apt-get install nginx
sudo ufw apt "Nginx HTTP"

echo "Hello world!" | sudo tee /var/www/html/index.html

# testing nginc configurations
sudo nginx -t 

sudo service nginx reload 
